name: Run Python After Checkmarx Scan

on:
  status:
    types: [completed]

jobs:
  run-python-if-checkmarx-passed:
    if: github.event.context == 'Checkmarx' && github.event.state == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script
        run: |
          echo "Running postscan.py..."
          python3 .github/scripts/postscan.py
