name: Run Python Script on PR Source Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-python-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script
        run: |
          echo "Running postscan.py..."
          python3 .github/scripts/postscan.py
